#!/usr/bin/env bash
# Rewrites Formula/tree-cleaner.rb so it installs the prebuilt binaries of a release.
#
# It runs after the release exists and its assets are uploaded, because a checksum can only
# be taken once the file is published. Requires `gh` authenticated for this repository.
#
#   scripts/release/update-formula.sh 0.3.0
set -euo pipefail

version="${1:?usage: update-formula.sh <version>}"
tag="v${version}"
repository="${FORMULA_REPOSITORY:-lf-bf/tree-cleaner}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
formula="${root}/Formula/tree-cleaner.rb"

command -v gh >/dev/null 2>&1 || { echo "gh is required to read the release assets" >&2; exit 1; }

download_directory="$(mktemp -d)"
trap 'rm -rf "${download_directory}"' EXIT
gh release download "${tag}" --repo "${repository}" --pattern '*.sha256' --dir "${download_directory}"

# Checksum of one target, as published next to its tarball.
checksum_of() {
  local target="$1"
  local file="${download_directory}/tree-cleaner-${tag}-${target}.tar.gz.sha256"
  if [[ ! -f "${file}" ]]; then
    echo "no checksum published for ${target} in ${tag}" >&2
    exit 1
  fi
  awk '{print $1}' "${file}"
}

macos_arm_sha="$(checksum_of aarch64-apple-darwin)"
macos_intel_sha="$(checksum_of x86_64-apple-darwin)"
linux_intel_sha="$(checksum_of x86_64-unknown-linux-gnu)"

download_url() {
  echo "https://github.com/${repository}/releases/download/${tag}/tree-cleaner-${tag}-$1.tar.gz"
}

cat > "${formula}" <<RUBY
# Homebrew formula for tree-cleaner.
#
#   brew tap lf-bf/tree-cleaner https://github.com/lf-bf/tree-cleaner.git
#   brew install tree-cleaner
#   brew upgrade tree-cleaner          # after \`brew update\`
#
# Generated by scripts/release/update-formula.sh after every release: it points at the
# prebuilt binaries of the tag and carries their checksums, so installing downloads a few
# hundred kilobytes instead of building a Rust toolchain. Do not edit the url or sha256
# lines by hand; Homebrew reads the version from the url.
#
# Platforms without a published binary (Linux on ARM, for example) build from source with
# \`brew install --HEAD tree-cleaner\` or \`cargo install tree-cleaner\`.
class TreeCleaner < Formula
  desc "Interactive terminal explorer and cleaner for disk usage"
  homepage "https://github.com/${repository}"
  license "MIT"

  head do
    url "https://github.com/${repository}.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "$(download_url aarch64-apple-darwin)"
      sha256 "${macos_arm_sha}"
    end
    on_intel do
      url "$(download_url x86_64-apple-darwin)"
      sha256 "${macos_intel_sha}"
    end
  end

  on_linux do
    on_intel do
      url "$(download_url x86_64-unknown-linux-gnu)"
      sha256 "${linux_intel_sha}"
    end
  end

  def install
    # The head build ships the sources; a release ships the binary on its own.
    if File.exist?("Cargo.toml")
      system "cargo", "install", *std_cargo_args
    else
      bin.install "tree-cleaner"
    end
  end

  test do
    assert_match "tree-cleaner #{version}", shell_output("#{bin}/tree-cleaner --version")
    system bin/"tree-cleaner", "categories"
  end
end
RUBY

if command -v ruby >/dev/null 2>&1; then
  ruby -c "${formula}" >/dev/null
fi
echo "formula now points at ${tag}"
