# Homebrew formula for tree-cleaner.
#
#   brew tap lf-bf/tree-cleaner https://github.com/lf-bf/tree-cleaner.git
#   brew install tree-cleaner
#   brew upgrade tree-cleaner          # after `brew update`
#
# Generated by scripts/release/update-formula.sh after every release: it points at the
# prebuilt binaries of the tag and carries their checksums, so installing downloads a few
# hundred kilobytes instead of building a Rust toolchain. Do not edit the url or sha256
# lines by hand; Homebrew reads the version from the url.
#
# Platforms without a published binary (Linux on ARM, for example) build from source with
# `brew install --HEAD tree-cleaner` or `cargo install tree-cleaner`.
class TreeCleaner < Formula
  desc "Interactive terminal explorer and cleaner for disk usage"
  homepage "https://github.com/lf-bf/tree-cleaner"
  license "MIT"

  head do
    url "https://github.com/lf-bf/tree-cleaner.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/lf-bf/tree-cleaner/releases/download/v0.3.0/tree-cleaner-v0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "ba0798a659cba6718081d1c7e4b76b3a9e32d030555918d32d1e16a0c8b16a7c"
    end
    on_intel do
      url "https://github.com/lf-bf/tree-cleaner/releases/download/v0.3.0/tree-cleaner-v0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "b5f73768f12d0f2ef3a6393432c483dbff9799b28c173a3b6c394c6b384d68f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lf-bf/tree-cleaner/releases/download/v0.3.0/tree-cleaner-v0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4dbb0dee2a5c92bc3cad0340307a102682ee699ff90c807756337e91e3eaba88"
    end
  end

  def install
    # The head build ships the sources; a release ships the binary on its own.
    if File.exist?("Cargo.toml")
      system "cargo", "install", *std_cargo_args
    else
      bin.install "tree-cleaner"
    end
  end

  test do
    assert_match "tree-cleaner #{version}", shell_output("#{bin}/tree-cleaner --version")
    system bin/"tree-cleaner", "categories"
  end
end
